update : github actions workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,6 +36,7 @@ jobs:
           PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
           HOST: ${{ secrets.EC2_HOST }}
           USER: ${{ secrets.EC2_USER }}
+          ENV_FILE: ${{ secrets.ENV_FILE }}
         run: |
           echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
           scp -o StrictHostKeyChecking=no -i private_key deploy.tar.gz ${USER}@${HOST}:~/ || (echo "fail - Deploy (copy deployment package to server)" && exit 1)
@@ -43,6 +44,7 @@ jobs:
             mkdir -p ~/stepmerrily
             tar -xzf deploy.tar.gz -C ~/stepmerrily || (echo "fail - Deploy (extract deployment package on server)" && exit 1)
             cd ~/stepmerrily
+            echo "$ENV_FILE" > .env || (echo "fail - Deploy (create .env file)" && exit 1)
             npm ci || (echo "fail - Deploy (install dependencies on server)" && exit 1)
             npx prisma generate || (echo "fail - Deploy (generate prisma client on server)" && exit 1)
             pm2 delete stepmerrily || true
